// app/villaer/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import ContactForm from "@/components/ContactForm";
import ImageGrid from "@/components/ImageGrid";
import CtaBand from "@/components/CtaBand";

export const metadata: Metadata = {
  title: "Arkitekttegnet villa — pris og projekter — Yderskov Arkitekter",
  description:
    "Arkitekttegnede villaer i Aalborg og Nordjylland. Se projekter, priser og proces for arkitekt nybyggeri. Gratis første møde.",
  alternates: { canonical: "https://yderskov.dk/villaer" },
};

const projectGalleries = [
  {
    eyebrow: "Projekt",
    title: "Funkis træ,\nglas og eternit.",
    location: "Sæby, Nordjylland",
    size: "230 m² bolig · 60 m² garage",
    year: "2023",
    description: "Funkisvilla opført i listebeklædning med åbne facader og store vinduespartier. Huset er beliggende op ad skov og natur, og det betød meget for familien at byggeriet blev indpasset omhyggeligt i det omgivende område.",
    images: [
      { src: "/images/Karetmagervej/IMG_9184.webp", alt: "Arkitekttegnet funkisvilla i Sæby — Yderskov Arkitekter" },
      { src: "/images/Karetmagervej/IMG_9182.webp", alt: "Arkitekttegnet funkisvilla i Sæby — Yderskov Arkitekter" },
      { src: "/images/Karetmagervej/IMG_9185.webp", alt: "Arkitekttegnet funkisvilla i Sæby — Yderskov Arkitekter" },
    ],
    dark: false,
  },
  {
    eyebrow: "Projekt",
    title: "Moderne villa\nmed markant tag.",
    images: [
      { src: "/images/villa sæby/IMG_2472.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/villa sæby/IMG_2473.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/villa sæby/IMG_2480.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
    ],
    dark: true,
  },
  {
    eyebrow: "Projekt",
    title: "Villa med\nnaturlige materialer.",
    images: [
      { src: "/images/Lerstien/IMG_7912.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Lerstien/IMG_7931.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Lerstien/IMG_7936.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
    ],
    dark: false,
  },
  {
    eyebrow: "Projekt",
    title: "Funkis\nvilla.",
    images: [
      { src: "/images/Højgården/IMG_2786.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Højgården/IMG_2787.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Højgården/IMG_2790.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
    ],
    dark: true,
  },
  {
    eyebrow: "Projekt",
    title: "Klassisk\nvilla.",
    images: [
      { src: "/images/Gartnerhaven/gartnehaven.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Gartnerhaven/IMG_2288.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Gartnerhaven/gårdmiljø.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
    ],
    dark: false,
  },
  {
    eyebrow: "Projekt",
    title: "Villa med\nensidig taghældning.",
    images: [
      { src: "/images/Hanebjælken/IMG_4752.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Hanebjælken/IMG_4754.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
      { src: "/images/Hanebjælken/IMG_4756.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" },
    ],
    dark: false,
  },
];

const faqItems = [
  {
    q: "Hvad koster det at bygge en arkitekttegnet villa?",
    a: "En arkitekttegnet villa starter typisk fra 15.000 kr. pr. m². Prisen afhænger af størrelse, materialer og kompleksitet. Kontakt os for en præcis vurdering.",
  },
  {
    q: "Hvad er forskellen på en arkitekttegnet villa og en typehus?",
    a: "En arkitekttegnet villa tegnes specifikt til din grund og dine ønsker. Et typehus er et standardiseret produkt. Vi tilpasser alt fra planløsning til facader.",
  },
  {
    q: "Hvor lang tid tager det at bygge en villa?",
    a: "Fra første møde til indflytning tager det typisk 12-18 måneder. Byggetiden afhænger af projektets kompleksitet og kommunens sagsbehandlingstid.",
  },
  {
    q: "Søger I byggetilladelse?",
    a: "Ja — vi håndterer hele myndighedsprocessen, herunder byggetilladelse, BR-krav og kommunal godkendelse.",
  },
  {
    q: "Arbejder I med faste priser?",
    a: "Ja. Vi tilbyder fast pris på arkitekthonoraret, så du altid kender dine udgifter. Ingen ubehagelige overraskelser undervejs.",
  },
  {
    q: "Hvad er jeres geografiske område?",
    a: "Vi arbejder primært i Nordjylland og Aalborg-området, men tager gerne projekter i hele Danmark.",
  },
];

export default function VillaerPage() {
  return (
    <>
      <Nav />
      <Hero
        slides={[{ src: "/images/Karetmagervej/IMG_9184.webp", alt: "Arkitekttegnet villa — Yderskov Arkitekter" }]}
        tag="Villaer"
        subtitle="Villaer"
        lines={[
          "Jeres villa skal fortælle jeres historie, fra første streg til sidste mursten.",
          "Gratis og uforpligtende første idemøde. Vi kommer ud til jer.",
        ]}
        italicLines={[0, 1]}
      />

      {/* Intro */}
      <section className="s">
        <div className="s-inner">
          <div className="text-2col">
            <div>
              <span className="eyebrow">Arkitekttegnede villaer</span>
              <h1 className="sec-hed">Arkitekttegnede villaer<br />fra idé til nøglefærdigt.</h1>
            </div>
            <div>
              <p className="body-p">
                Hvert villaprojekt starter med en grundig dialog om jeres ønsker, behov og økonomi. Vi tegner, projekterer og bygger — med egne håndværkere og ét samlet ansvar.
              </p>
              <p className="body-p">
                Se vores projekter og lad dig inspirere. Kontakt os for et gratis første møde direkte på grunden.
              </p>
              <p className="body-p">
                <Link href="#kontakt" className="text-link">→ Kom i gang</Link>
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Project galleries */}
      {projectGalleries.map((gallery, i) => (
        <section key={i} className={`s${gallery.dark ? " s-off" : ""}`}>
          <div className="s-inner">
            <div className="proj-header">
              <div>
                <span className="eyebrow">{gallery.eyebrow}</span>
                <h2 className="sec-hed" style={{ marginBottom: 0, whiteSpace: "pre-line" }}>
                  {gallery.title}
                </h2>
                {"location" in gallery && (
                  <p className="proj-meta">
                    {gallery.location}{gallery.size ? ` · ${gallery.size}` : ""}{gallery.year ? ` · ${gallery.year}` : ""}
                  </p>
                )}
                {"description" in gallery && (
                  <p className="proj-desc">{gallery.description}</p>
                )}
              </div>
            </div>
            <ImageGrid images={gallery.images} />
          </div>
        </section>
      ))}

      {/* Stats */}
      <div className="stats-bg">
        <div className="stats-inner">
          <div className="stat">
            <div className="stat-num">15.000<sup> kr.</sup></div>
            <div className="stat-lbl">Fra pr. m²</div>
          </div>
          <div className="stat">
            <div className="stat-num">24<sup> timer</sup></div>
            <div className="stat-lbl">Svar inden</div>
          </div>
          <div className="stat">
            <div className="stat-num">10<sup>+</sup></div>
            <div className="stat-lbl">Igangværende projekter</div>
          </div>
          <div className="stat">
            <div className="stat-num">300<sup>+</sup></div>
            <div className="stat-lbl">Projekter gennemført</div>
          </div>
        </div>
      </div>

      {/* FAQ */}
      <section className="s">
        <div className="s-inner">
          <span className="eyebrow">Spørgsmål og svar</span>
          <h2 className="sec-hed">FAQ — villaer</h2>
          <div className="faq-grid">
            {faqItems.map((item, i) => (
              <div key={i} className="faq-item">
                <p className="faq-q">{item.q}</p>
                <p className="faq-a">{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <CtaBand />

      {/* Contact form */}
      <section className="s form-bg" id="kontakt">
        <div className="s-inner">
          <div className="form-layout">
            <div className="form-meta">
              <span className="eyebrow">Kontakt os</span>
              <h2 className="sec-hed">Lad os skabe<br />dit drømmehus</h2>
              <p style={{ marginTop: "1.5rem" }}>Ring eller skriv til os. Vi svarer inden 24 timer og tilbyder et gratis, uforpligtende møde direkte på grunden.</p>
              <p><a href="tel:29723427">29 72 34 27</a></p>
              <p><a href="mailto:cy@yderskov.com">cy@yderskov.com</a></p>
            </div>
            <ContactForm />
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

// src/routes/villaer/+page.svelte
<script lang="ts">
	import Hero from '$lib/components/Hero.svelte';
	import ContactForm from '$lib/components/ContactForm.svelte';
	import ImageGrid from '$lib/components/ImageGrid.svelte';
	import CtaBand from '$lib/components/CtaBand.svelte';
	import InspirationGallery from '$lib/components/InspirationGallery.svelte';
	import ProjectDescription from '$lib/components/ProjectDescription.svelte';
	import Breadcrumbs from '$lib/components/Breadcrumbs.svelte';
	import { projectGalleries, faqItems } from '$lib/data/villaer';

	const projectSchema = $derived({
		'@context': 'https://schema.org',
		'@graph': projectGalleries.map((p: any) => {
			const floorSizeMatch = p.size.match(/(\d+)\s*m²\s*bolig/);
			const floorSize = floorSizeMatch ? parseInt(floorSizeMatch[1]) : undefined;
			const locality = p.location.split(',')[0].trim();
			return {
				'@type': 'SingleFamilyResidence',
				name: p.title.replace(/\n/g, ' '),
				description: p.description.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1'),
				address: {
					'@type': 'PostalAddress',
					addressLocality: locality,
					addressCountry: 'DK'
				},
				image: p.images.map((img: any) => `https://yderskov.com${img.src}`),
				architect: {
					'@type': 'LocalBusiness',
					name: 'Yderskov Arkitekter',
					url: 'https://yderskov.com/'
				},
				yearBuilt: p.year ? parseInt(p.year) : undefined,
				floorSize: floorSize
					? {
							'@type': 'QuantitativeValue',
							value: floorSize,
							unitText: 'm²'
						}
					: undefined
			};
		})
	});
</script>

<svelte:head>
	<title>Arkitekttegnet villa — Se priser & projekter | Yderskov</title>
	<meta
		name="description"
		content="Drømmer du om en arkitekttegnet villa? Se projekter, priser og byggeproces hos Yderskov. Vi tilbyder fast pris, egne håndværkere & gratis første møde."
	/>
	<link rel="canonical" href="https://yderskov.com/villaer" />
	<meta property="og:type" content="website" />
	<meta property="og:locale" content="da_DK" />
	<meta property="og:url" content="https://yderskov.com/villaer" />
	<meta property="og:siteName" content="Yderskov Arkitekter" />
	<meta property="og:image" content="https://yderskov.com/images/Karetmagervej/Sæby-ny-villa-funkis-forside.webp" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Arkitekttegnet villa — Se priser & projekter | Yderskov" />
	<meta
		name="twitter:description"
		content="Drømmer du om en arkitekttegnet villa? Se projekter, priser og byggeproces hos Yderskov. Vi tilbyder fast pris, egne håndværkere & gratis første møde."
	/>
	<meta name="twitter:image" content="https://yderskov.com/images/Karetmagervej/Sæby-ny-villa-funkis-forside.webp" />
	{@html `<script type="application/ld+json">${JSON.stringify(projectSchema).replace(/</g, '\\u003c')}</script>`}
</svelte:head>

<Hero
	slides={[
		{ src: '/images/Karetmagervej/Sæby-ny-villa-funkis-haveside.webp', alt: 'Arkitekttegnet villa — Arkitekttegnestuen Yderskov' }
	]}
	tag="Villaer"
	subtitle="Villaer"
	lines={[
		'Jeres villa skal fortælle jeres historie, fra første streg til sidste mursten.',
		'Gratis og uforpligtende første idemøde. Vi kommer ud til jer.'
	]}
	italicLines={[0, 1]}
/>
<Breadcrumbs items={[{ label: 'Villaer' }]} />

<!-- Intro -->
<section class="s">
	<div class="s-inner">
		<div class="text-2col">
			<div>
				<span class="eyebrow">Arkitekttegnede villaer</span>
				<h1 class="sec-hed">Arkitekttegnede villaer<br />fra idé til nøglefærdigt.</h1>
			</div>
			<div>
				<p class="body-p">
					Hvert villaprojekt starter med en grundig dialog om jeres ønsker, behov og økonomi. Vi tegner, projekterer og bygger — med egne håndværkere og ét samlet ansvar. Som jeres <a href="/arkitekt-aalborg" class="text-link">arkitekt i Aalborg</a> og resten af landet hjælper vi jer hele vejen. Læs mere om <a href="/om" class="text-link">vores tegnestue</a> eller få et overblik over <a href="/priser" class="text-link">vores prissatser</a>.
				</p>
				<p class="body-p">
					Se vores projekter og lad dig inspirere. Kontakt os for et gratis første møde direkte på grunden.
				</p>
				<p class="body-p">
					<a href="#kontakt" class="text-link">→ Kom i gang</a>
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Project galleries -->
{#each projectGalleries as gallery, i (i)}
	<section class={`s${gallery.dark ? ' s-off' : ''}`}>
		<div class="s-inner">
			<div class="proj-header">
				<div>
					<span class="eyebrow">{gallery.eyebrow}</span>
					<h2 class="sec-hed" style="margin-bottom: 0; white-space: pre-line;">
						{gallery.title}
					</h2>
					{#if gallery.location}
						<p class="proj-meta">
							{gallery.location}{gallery.size ? ` · ${gallery.size}` : ''}{gallery.year ? ` · ${gallery.year}` : ''}
						</p>
					{/if}
					{#if gallery.description}
						<ProjectDescription text={gallery.description} />
					{/if}
				</div>
			</div>
			<ImageGrid images={gallery.images} />
		</div>
	</section>
{/each}

<!-- FAQ -->
<section class="s">
	<div class="s-inner">
		<span class="eyebrow">Spørgsmål og svar</span>
		<h2 class="sec-hed">FAQ — villaer</h2>
		<div class="faq-grid">
			{#each faqItems as item, i (i)}
				<div class="faq-item">
					<p class="faq-q">{item.q}</p>
					<p class="faq-a">{item.a}</p>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- Inspiration Galleri -->
<section class="s s-off">
	<div class="s-inner">
		<span class="eyebrow">Galleri</span>
		<h2 class="sec-hed">Inspiration</h2>
		<InspirationGallery />
	</div>
</section>

<CtaBand />

<!-- Contact form -->
<section class="s form-bg" id="kontakt">
	<div class="s-inner">
		<div class="form-layout">
			<div class="form-meta">
				<span class="eyebrow">Kontakt os</span>
				<h2 class="sec-hed">Lad os skabe<br />dit drømmehus</h2>
				<p style="margin-top: 1.5rem;">Ring eller skriv til os. Vi svarer inden 24 timer og tilbyder et gratis, uforpligtende møde direkte på grunden.</p>
				<p><a href="tel:29723427">29 72 34 27</a></p>
				<p><a href="mailto:cy@yderskov.com">cy@yderskov.com</a></p>
			</div>
			<ContactForm />
		</div>
	</div>
</section>
