// src/lib/components/Nav.svelte
<script lang="ts">
	import { page } from '$app/state';

	type Child = { href: string; label: string };
	type NavItem =
		| { href: string; label: string; children?: undefined }
		| { href?: undefined; label: string; children: Child[] };

	const navItems: NavItem[] = [
		{ href: '/', label: 'Hjem' },
		{
			label: 'Projekter',
			children: [
				{ href: '/villaer', label: 'Villaer' },
				{ href: '/sommerhuse', label: 'Sommerhuse' },
				{ href: '/tilbygninger', label: 'Om- og tilbygninger' },
				{ href: '/lejligheder', label: 'Lejligheder' },
				{ href: '/special', label: 'Special' },
				{ href: '/erhverv', label: 'Erhverv' },
				{ href: '/inspiration', label: 'Inspiration' }
			]
		},
		{
			label: 'Priser',
			children: [
				{ href: '/priser', label: 'Se priser' },
				{ href: '/prisberegner', label: 'Prisberegner' }
			]
		},
		{ href: '/blog', label: 'Blog' },
		{
			label: 'Om os',
			children: [
				{ href: '/om', label: 'Om tegnestuen' },
				{ href: '/arkitekt-aalborg', label: 'Arkitekt Aalborg' },
				{ href: '/arkitekt-sjaelland', label: 'Arkitekt Sjælland' }
			]
		},
		{ href: '/faq', label: 'FAQ' }
	];

	let open = $state(false);
	let activeDropdown = $state<string | null>(null);
	let dropdownLeft = $state(0);
	let innerRef: HTMLDivElement | null = $state(null);

	const pathname = $derived(page.url.pathname);

	$effect(() => {
		document.body.classList.toggle('menu-open', open);
		return () => document.body.classList.remove('menu-open');
	});

	// Close menus whenever the route changes
	$effect(() => {
		page.url.pathname;
		open = false;
		activeDropdown = null;
	});

	$effect(() => {
		if (!activeDropdown) return;
		const handler = (e: MouseEvent) => {
			if (innerRef && !innerRef.contains(e.target as Node)) {
				activeDropdown = null;
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	});

	function isGroupActive(item: NavItem): boolean {
		return item.children?.some((c) => pathname === c.href) ?? false;
	}

	const activeItem = $derived(navItems.find((i) => i.label === activeDropdown));

	function toggle(label: string, e: MouseEvent) {
		if (activeDropdown === label) {
			activeDropdown = null;
			return;
		}
		const inner = innerRef;
		const btn = e.currentTarget as HTMLButtonElement;
		if (inner && btn) {
			const innerRect = inner.getBoundingClientRect();
			const btnRect = btn.getBoundingClientRect();
			dropdownLeft = btnRect.left - innerRect.left + btnRect.width / 2;
		}
		activeDropdown = label;
	}

	function handleLinkClick(e: MouseEvent, href?: string) {
		if (href === '/' && pathname === '/') {
			e.preventDefault();
			window.scrollTo(0, 0);
		}
		open = false;
	}
</script>

<nav>
	<div class="nav-inner" bind:this={innerRef}>
		<a href="/" class="nav-logo" aria-label="Yderskov Arkitekter — forside" onclick={(e) => handleLinkClick(e, '/')}>
			<img src="/images/logofiles/SVG/Arkitect 5icon.svg" alt="Arkitekttegnestuen Yderskov logo" width="30" height="30" />
		</a>

		<ul class="nav-links">
			{#each navItems as item (item.label)}
				{#if item.children}
					<li class="nav-has-dropdown">
						<button
							class={`nav-dropdown-trigger${isGroupActive(item) ? ' nav-active' : ''}${activeDropdown === item.label ? ' nav-dropdown-open' : ''}`}
							onclick={(e) => toggle(item.label, e)}
						>
							{item.label}
							<svg class="nav-arrow" width="9" height="7" viewBox="0 0 9 7" aria-hidden="true">
								<path d="M0.5 1L4.5 5.5L8.5 1" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
							</svg>
						</button>
					</li>
				{:else}
					<li>
						<a
							href={item.href}
							class={pathname === item.href ? 'nav-active' : ''}
							onclick={(e) => handleLinkClick(e, item.href)}
						>
							{item.label}
						</a>
					</li>
				{/if}
			{/each}
		</ul>

		<div class="nav-actions">
			<a href="tel:29723427" class="nav-phone" aria-label="Ring 29 72 34 27">
				<span class="nav-phone-icon" aria-hidden="true">
					<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.93.37 1.84.72 2.71a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.37-1.29a2 2 0 0 1 2.11-.45c.87.35 1.78.59 2.71.72A2 2 0 0 1 22 16.92z"/></svg>
				</span>
				29 72 34 27
			</a>

			<a href="/kontakt#heroContactForm" class="nav-book-btn">Book gratis møde</a>
		</div>

		<button class={`hamburger${open ? ' active' : ''}`} onclick={() => (open = !open)} aria-label="Menu">
			<span /><span /><span />
		</button>

		{#if activeDropdown && activeItem?.children}
			<ul class="nav-dropdown" style={`left: ${dropdownLeft}px`}>
				{#each activeItem.children as c (c.href)}
					<li>
						<a
							href={c.href}
							class={pathname === c.href ? 'nav-active' : ''}
							onclick={(e) => handleLinkClick(e, c.href)}
						>
							{c.label}
						</a>
					</li>
				{/each}
			</ul>
		{/if}
	</div>

	{#if open}
		<div class="nav-mobile-menu">
			<a href="/kontakt#heroContactForm" class="nav-mobile-book" onclick={(e) => handleLinkClick(e, '/kontakt#heroContactForm')}>
				Book gratis møde
			</a>
			<a href="/kontakt" class="nav-mobile-link" style="font-weight: 500; margin-top: 0.5rem; margin-bottom: 1rem;" onclick={(e) => handleLinkClick(e, '/kontakt')}>
				Kontakt
			</a>
			{#each navItems as item (item.label)}
				{#if item.children}
					<div class="nav-mobile-group">
						<span class="nav-mobile-group-label">{item.label}</span>
						{#each item.children.filter((c) => c.href !== '/arkitekt-aalborg' && c.href !== '/arkitekt-sjaelland') as c (c.href)}
							<a
								href={c.href}
								class={`nav-mobile-link${pathname === c.href ? ' nav-active' : ''}`}
								onclick={(e) => handleLinkClick(e, c.href)}
							>
								{c.label}
							</a>
						{/each}
					</div>
				{:else}
					<a
						href={item.href}
						class={`nav-mobile-link${pathname === item.href ? ' nav-active' : ''}`}
						onclick={(e) => handleLinkClick(e, item.href)}
					>
						{item.label}
					</a>
				{/if}
			{/each}
		</div>
	{/if}
</nav>

// components/Nav.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, useEffect, useRef } from "react";

type Child = { href: string; label: string };
type NavItem =
  | { href: string; label: string; children?: undefined }
  | { href?: undefined; label: string; children: Child[] };

const navItems: NavItem[] = [
  { href: "/", label: "Hjem" },
  {
    label: "Projekter",
    children: [
      { href: "/villaer", label: "Villaer" },
      { href: "/sommerhuse", label: "Sommerhuse" },
      { href: "/tilbygninger", label: "Om- og tilbygninger" },
      { href: "/lejligheder", label: "Lejligheder" },
      { href: "/special", label: "Special" },
      { href: "/erhverv", label: "Erhverv" },
      { href: "/inspiration", label: "Inspiration" },
    ],
  },
  {
    label: "Priser",
    children: [
      { href: "/priser", label: "Se priser" },
      { href: "/prisberegner", label: "Prisberegner" },
    ],
  },
  { href: "/blog", label: "Blog" },

  {
    label: "Om os",
    children: [
      { href: "/om", label: "Om tegnestuen" },
      { href: "/arkitekt-aalborg", label: "Arkitekt Aalborg" },
      { href: "/arkitekt-sjaelland", label: "Arkitekt Sjælland" },
    ],
  },
  { href: "/faq", label: "FAQ" },
];

export default function Nav() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);
  const [activeDropdown, setActiveDropdown] = useState<string | null>(null);
  const [dropdownLeft, setDropdownLeft] = useState<number>(0);
  const innerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    document.body.classList.toggle("menu-open", open);
    return () => document.body.classList.remove("menu-open");
  }, [open]);

  useEffect(() => {
    const raf = requestAnimationFrame(() => {
      setOpen(false);
      setActiveDropdown(null);
    });
    return () => cancelAnimationFrame(raf);
  }, [pathname]);



  useEffect(() => {
    if (!activeDropdown) return;
    const handler = (e: MouseEvent) => {
      if (innerRef.current && !innerRef.current.contains(e.target as Node)) {
        setActiveDropdown(null);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [activeDropdown]);

  const toggle = (label: string, e: React.MouseEvent<HTMLButtonElement>) => {
    if (activeDropdown === label) {
      setActiveDropdown(null);
      return;
    }
    const inner = innerRef.current;
    const btn = e.currentTarget;
    if (inner && btn) {
      const innerRect = inner.getBoundingClientRect();
      const btnRect = btn.getBoundingClientRect();
      setDropdownLeft(btnRect.left - innerRect.left + btnRect.width / 2);
    }
    setActiveDropdown(label);
  };


  const isGroupActive = (item: NavItem) =>
    item.children?.some((c) => pathname === c.href) ?? false;

  const activeItem = navItems.find((i) => i.label === activeDropdown);

  const handleLinkClick = (e: React.MouseEvent, href?: string) => {
    if (href === "/" && pathname === "/") {
      e.preventDefault();
      window.scrollTo(0, 0);
    }
    setOpen(false);
  };

  return (
    <nav>
      <div className="nav-inner" ref={innerRef}>
        <Link href="/" className="nav-logo" aria-label="Yderskov Arkitekter — forside" onClick={(e) => handleLinkClick(e, "/")}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/images/logofiles/SVG/Arkitect 5icon.svg" alt="Arkitekttegnestuen Yderskov logo" width={30} height={30} />
        </Link>

        <ul className="nav-links">
          {navItems.map((item) =>
            item.children ? (
              <li key={item.label} className="nav-has-dropdown">
                <button
                  className={`nav-dropdown-trigger${isGroupActive(item) ? " nav-active" : ""}${activeDropdown === item.label ? " nav-dropdown-open" : ""}`}
                  onClick={(e) => toggle(item.label, e)}
                >
                  {item.label}
                  <svg className="nav-arrow" width="9" height="7" viewBox="0 0 9 7" aria-hidden="true">
                    <path d="M0.5 1L4.5 5.5L8.5 1" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </button>
              </li>
            ) : (
              <li key={item.href}>
                <Link
                  href={item.href}
                  className={pathname === item.href ? "nav-active" : ""}
                  onClick={(e) => handleLinkClick(e, item.href)}
                >
                  {item.label}
                </Link>
              </li>
            )
          )}
        </ul>

        <div className="nav-actions">
          <a href="tel:29723427" className="nav-phone" aria-label="Ring 29 72 34 27">
            <span className="nav-phone-icon" aria-hidden="true">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.93.37 1.84.72 2.71a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.37-1.29a2 2 0 0 1 2.11-.45c.87.35 1.78.59 2.71.72A2 2 0 0 1 22 16.92z"/></svg>
            </span>
            29 72 34 27
          </a>

          <Link href="/kontakt#heroContactForm" className="nav-book-btn">
            Book gratis møde
          </Link>
        </div>

        <button
          className={`hamburger${open ? " active" : ""}`}
          onClick={() => setOpen((v) => !v)}
          aria-label="Menu"
        >
          <span /><span /><span />
        </button>

        {activeDropdown && activeItem?.children && (
          <ul className="nav-dropdown" style={{ left: dropdownLeft }}>
            {activeItem.children.map((c) => (
              <li key={c.href}>
                <Link
                  href={c.href}
                  className={pathname === c.href ? "nav-active" : ""}
                  onClick={(e) => handleLinkClick(e, c.href)}
                >
                  {c.label}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>

      {open && (
        <div className="nav-mobile-menu">
          <Link href="/kontakt#heroContactForm" className="nav-mobile-book" onClick={(e) => handleLinkClick(e, "/kontakt#heroContactForm")}>
            Book gratis møde
          </Link>
          <Link href="/kontakt" className="nav-mobile-link" style={{ fontWeight: 500, marginTop: "0.5rem", marginBottom: "1rem" }} onClick={(e) => handleLinkClick(e, "/kontakt")}>
            Kontakt
          </Link>
          {navItems.map((item) =>
            item.children ? (
              <div key={item.label} className="nav-mobile-group">
                <span className="nav-mobile-group-label">{item.label}</span>
                {item.children.filter((c) => c.href !== "/arkitekt-aalborg" && c.href !== "/arkitekt-sjaelland").map((c) => (
                  <Link
                    key={c.href}
                    href={c.href}
                    className={`nav-mobile-link${pathname === c.href ? " nav-active" : ""}`}
                    onClick={(e) => handleLinkClick(e, c.href)}
                  >
                    {c.label}
                  </Link>
                ))}
              </div>
            ) : (
              <Link
                key={item.href}
                href={item.href}
                className={`nav-mobile-link${pathname === item.href ? " nav-active" : ""}`}
                onClick={(e) => handleLinkClick(e, item.href)}
              >
                {item.label}
              </Link>
            )
          )}
        </div>
      )}
    </nav>
  );
}
