// app/erhverv/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import ContactForm from "@/components/ContactForm";
import ImageGrid from "@/components/ImageGrid";
import CtaBand from "@/components/CtaBand";
import InspirationGallery from "@/components/InspirationGallery";
import ProjectDescription from "@/components/ProjectDescription";
import Breadcrumbs from "@/components/Breadcrumbs";

export const metadata: Metadata = {
  title: "Erhvervsbyggeri — Arkitekttegnede kontorer | Yderskov",
  description:
    "Vi tegner erhvervsbyggeri, der matcher jeres behov — fra kontorer til udlejningsboliger og ombygninger. Få arkitektrådgivning til aftalt fast pris.",
  alternates: { canonical: "https://yderskov.com/erhverv" },
  openGraph: {
    type: "website",
    locale: "da_DK",
    url: "https://yderskov.com/erhverv",
    siteName: "Yderskov Arkitekter",
    images: [{ url: "https://yderskov.com/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Erhvervsbyggeri — Arkitekttegnede kontorer | Yderskov",
    description: "Vi tegner erhvervsbyggeri, der matcher jeres behov — fra kontorer til udlejningsboliger og ombygninger. Få arkitektrådgivning til aftalt fast pris.",
    images: ["https://yderskov.com/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp"],
  },
};

const projectGalleries = [
  {
    eyebrow: "Projekt",
    title: "Kontormiljø\nfor IT-virksomhed, Aalborg.",
    location: "Aalborg, Nordjylland",
    size: "320 m² kontor og faciliteter",
    year: "2022",
    description: "Vi har tegnet og indrettet dette åbne kontormiljø for en IT-virksomhed i Aalborg. For at skabe et godt arbejdsmiljø har vi fokuseret på at lukke masser af dagslys ind i alle lokaler. Mødelokaler og kontorer er opdelt med glasvægge, som har fået materede detaljer. Det gør det muligt at holde møder ugeneret og uden indkig, samtidig med at kontoret bevarer sin lyse og åbne rumfornemmelse.",
    images: [
      { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp", alt: "Kontormiljø for IT-virksomhed, Aalborg — Arkitekttegnestuen Yderskov" },
      { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø-kontor.webp", alt: "Kontor i kontormiljø, Aalborg — Arkitekttegnestuen Yderskov" },
      { src: "/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø-glasvæg.webp", alt: "Glasvæg i kontormiljø, Aalborg — Arkitekttegnestuen Yderskov" },
    ],
    dark: false,
  },
  {
    eyebrow: "Projekt",
    title: "Fabrik ombygget\ntil lejligheder i bycentrum, Aarhus.",
    location: "Aarhus Centrum",
    size: "1.200 m² (12 lejligheder)",
    year: "2021",
    description: "Da vi overtog projektet, blev den nedlagte fabriksbygning brugt som kostumelager for Aarhus Teater. Vi har bygget den om til 12 moderne og lyse lejligheder i Aarhus centrum. For at bevare bygningens historie og rå stemning, har vi beholdt de gamle rå murstensvægge, de synlige stålspær og de store, industrielle sprossevinduer, som giver et fantastisk lysindfald. Lejlighederne er indrettet enkelt med funktionelle køkkener, der passer godt til stilen. Flere af lejlighederne har fået deres egen private altan, så beboerne kan nyde udelivet midt i byen.",
    images: [
      { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget-køkken-og-altan.webp", alt: "Køkken og altan i ombygget fabrik, Aarhus — Arkitekttegnestuen Yderskov" },
    ],
    afterLabel: "Efter renovering",
    beforeLabel: "Før renovering",
    beforeImages: [
      { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget.webp", alt: "Ombygget fabrik i Aarhus centrum — Arkitekttegnestuen Yderskov" },
      { src: "/images/Fabrik Aarhus/Aarhus-fabrik-ombygget-lejligheder.webp", alt: "Fabrik ombygget til lejligheder i Aarhus — Arkitekttegnestuen Yderskov" },
    ],
    dark: true,
  },
  {
    eyebrow: "Projekt",
    title: "Udlejningsboliger,\nHals.",
    location: "Hals, Nordjylland",
    size: "6 boliger á 85-95 m²",
    year: "2023",
    description: "Vi har tegnet flere nye rækkehuse som udlejningsboliger i Hals. Husene er opført i gode materialer, der kræver minimal vedligeholdelse, med en flot kombination af lyse mursten og lodret, mørkt træværk. Hver bolig har sit eget indgangsparti, en lille nem og privat have samt en rigtig god indretning på 85-95 kvadratmeter. Boligerne er tegnet, så de udnytter dagslyset bedst muligt og henvender sig bredt til både yngre og ældre lejere.",
    images: [
      { src: "/images/Hals Rækkehuse/Hals-Aalborgvej20-udlejning-indgangsparti.webp", alt: "Indgangsparti, udlejningsboliger i Hals — Arkitekttegnestuen Yderskov" },
      { src: "/images/Hals Rækkehuse/Hals-Aalborgvej30-udlejning-.webp", alt: "Udlejningsbolig, Hals — Arkitekttegnestuen Yderskov" },
      { src: "/images/Hals Rækkehuse/Hals-Aalborgvej40-udlejning-.webp", alt: "Udlejningsbolig, Hals — Arkitekttegnestuen Yderskov" },
    ],
    dark: false,
  },
];

const faqItems = [
  {
    q: "Hvad koster erhvervsbyggeri med arkitekt?",
    a: "Prisen afhænger af projektets type og omfang. Vi giver et præcist tilbud baseret på jeres behov og ønsker.",
  },
  {
    q: "Hvilke typer erhvervsprojekter arbejder I med?",
    a: "Vi tegner kontorer, butikker, lager, produktionslokaler, restauranter og andre erhvervsbygninger.",
  },
  {
    q: "Håndterer I myndighedsgodkendelse for erhverv?",
    a: "Ja — vi søger og håndterer alle nødvendige tilladelser og godkendelser fra kommunen.",
  },
  {
    q: "Kan I tilpasse eksisterende erhvervslokaler?",
    a: "Absolut. Vi tegner ombygning og renovering af eksisterende erhvervslokaler til nye formål.",
  },
];

export default function ErhvervPage() {
  const projectSchema = {
    "@context": "https://schema.org",
    "@graph": projectGalleries.map((p) => {
      const location = p.title.split(",").pop()?.trim().replace(".", "").replace(/\n/g, " ") || "Danmark";
      const isApartment = p.title.toLowerCase().includes("lejlighed") || p.title.toLowerCase().includes("bolig");
      const images = [
        ...p.images.map((img) => `https://yderskov.com${img.src}`),
        ...('beforeImages' in p && Array.isArray(p.beforeImages) ? p.beforeImages.map((img) => `https://yderskov.com${img.src}`) : [])
      ];
      return {
        "@type": isApartment ? "ApartmentComplex" : "CommercialProperty",
        "name": p.title.replace(/\n/g, " "),
        "description": `Arkitekttegnet erhvervs- eller boligbyggeri i ${location} udført af Yderskov Arkitekter.`,
        "address": {
          "@type": "PostalAddress",
          "addressLocality": location,
          "addressCountry": "DK",
        },
        "image": images,
        "architect": {
          "@type": "LocalBusiness",
          "name": "Yderskov Arkitekter",
          "url": "https://yderskov.com/",
        },
      };
    }),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(projectSchema) }}
      />
      <Breadcrumbs items={[{ label: "Erhverv" }]} />
      <Nav />
      <Hero
        slides={[{ src: "/images/Hals Rækkehuse/Hals-Aalborgvej40-udlejning-.webp", alt: "Udlejningsboliger i Hals — Arkitekttegnestuen Yderskov" }]}
        tag="Erhverv"
        subtitle="Erhverv"
        lines={[
          "Dine rammer sætter tonen for din forretning. Lad os tegne dem.",
          "Gratis og uforpligtende første idemøde. Vi kommer ud til jer.",
        ]}
        italicLines={[0, 1]}
      />

      <section className="s">
        <div className="s-inner">
          <div className="text-2col">
            <div>
              <span className="eyebrow">Erhvervsbyggeri</span>
              <h1 className="sec-hed">Erhvervsbyggeri<br />tegnet til jeres behov.</h1>
            </div>
            <div>
              <p className="body-p">
                Vi tegner erhvervsbyggeri der afspejler jeres virksomhed — fra funktionelle kontorlokaler til produktionsfaciliteter med arkitektonisk identitet. Læs mere om <Link href="/om" className="text-link">vores samlede proces</Link> eller se vores generelle <Link href="/priser" className="text-link">priser på erhverv og bolig</Link>.
              </p>
              <p className="body-p">
                Vi håndterer hele processen fra idé til indvielse — med focus på jeres budget og tidsplan.
              </p>
              <p className="body-p">
                <Link href="#kontakt" className="text-link">→ Fortæl os om jeres projekt</Link>
              </p>
            </div>
          </div>
        </div>
      </section>

      {projectGalleries.map((gallery, i) => (
        <section key={i} className={`s${gallery.dark ? " s-off" : ""}`}>
          <div className="s-inner">
            <div className="proj-header">
              <div>
                <span className="eyebrow">{gallery.eyebrow}</span>
                {"beforeImages" in gallery && gallery.beforeImages && (
                  <span className="proj-ba-badge">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                      <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.85 1 6.5 2.5" />
                      <path d="M21 3v6h-6" />
                    </svg>
                    Før / Efter
                  </span>
                )}
                <h2 className="sec-hed" style={{ marginBottom: 0, whiteSpace: "pre-line" }}>
                  {gallery.title}
                </h2>
                {"location" in gallery && gallery.location && (
                  <p className="proj-meta">
                    {gallery.location}{gallery.size ? ` · ${gallery.size}` : ""}{gallery.year ? ` · ${gallery.year}` : ""}
                  </p>
                )}
                {"description" in gallery && gallery.description && (
                  <ProjectDescription text={gallery.description} />
                )}
              </div>
            </div>
            {"afterLabel" in gallery && <p className="proj-grid-label">{gallery.afterLabel}</p>}
            <ImageGrid images={gallery.images} />
            {"beforeImages" in gallery && gallery.beforeImages && (
              <>
                <p className="proj-grid-label" style={{ marginTop: "2rem" }}>{gallery.beforeLabel}</p>
                <ImageGrid images={gallery.beforeImages} />
              </>
            )}
          </div>
        </section>
      ))}


      <section className="s">
        <div className="s-inner">
          <span className="eyebrow">Spørgsmål og svar</span>
          <h2 className="sec-hed">FAQ — erhverv</h2>
          <div className="faq-grid">
            {faqItems.map((item, i) => (
              <div key={i} className="faq-item">
                <p className="faq-q">{item.q}</p>
                <p className="faq-a">{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Inspiration Galleri */}
      <section className="s s-off">
        <div className="s-inner">
          <span className="eyebrow">Galleri</span>
          <h2 className="sec-hed">Inspiration</h2>
          <InspirationGallery />
        </div>
      </section>

      <CtaBand />

      <section className="s form-bg" id="kontakt">
        <div className="s-inner">
          <div className="form-layout">
            <div className="form-meta">
              <span className="eyebrow">Kontakt os</span>
              <h2 className="sec-hed">Fortæl os om<br />jeres erhvervsprojekt</h2>
              <p style={{ marginTop: "1.5rem" }}>Ring eller skriv til os. Vi svarer inden 24 timer.</p>
              <p><a href="tel:29723427">29 72 34 27</a></p>
              <p><a href="mailto:cy@yderskov.com">cy@yderskov.com</a></p>
            </div>
            <ContactForm />
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

// src/routes/erhverv/+page.svelte
<script lang="ts">
	import Hero from '$lib/components/Hero.svelte';
	import ContactForm from '$lib/components/ContactForm.svelte';
	import ImageGrid from '$lib/components/ImageGrid.svelte';
	import CtaBand from '$lib/components/CtaBand.svelte';
	import InspirationGallery from '$lib/components/InspirationGallery.svelte';
	import ProjectDescription from '$lib/components/ProjectDescription.svelte';
	import Breadcrumbs from '$lib/components/Breadcrumbs.svelte';
	import { projectGalleries, faqItems } from '$lib/data/erhverv';

	const projectSchema = $derived({
		'@context': 'https://schema.org',
		'@graph': projectGalleries.map((p: any) => {
			const location = p.title.split(',').pop()?.trim().replace('.', '').replace(/\n/g, ' ') || 'Danmark';
			const isApartment = p.title.toLowerCase().includes('lejlighed') || p.title.toLowerCase().includes('bolig');
			const images = [
				...p.images.map((img: any) => `https://yderskov.com${img.src}`),
				...('beforeImages' in p && Array.isArray(p.beforeImages)
					? p.beforeImages.map((img: any) => `https://yderskov.com${img.src}`)
					: [])
			];
			return {
				'@type': isApartment ? 'ApartmentComplex' : 'CommercialProperty',
				name: p.title.replace(/\n/g, ' '),
				description: `Arkitekttegnet erhvervs- eller boligbyggeri i ${location} udført af Yderskov Arkitekter.`,
				address: {
					'@type': 'PostalAddress',
					addressLocality: location,
					addressCountry: 'DK'
				},
				image: images,
				architect: {
					'@type': 'LocalBusiness',
					name: 'Yderskov Arkitekter',
					url: 'https://yderskov.com/'
				}
			};
		})
	});
</script>

<svelte:head>
	<title>Erhvervsbyggeri — Arkitekttegnede kontorer | Yderskov</title>
	<meta
		name="description"
		content="Vi tegner erhvervsbyggeri, der matcher jeres behov — fra kontorer til udlejningsboliger og ombygninger. Få arkitektrådgivning til aftalt fast pris."
	/>
	<link rel="canonical" href="https://yderskov.com/erhverv" />
	<meta property="og:type" content="website" />
	<meta property="og:locale" content="da_DK" />
	<meta property="og:url" content="https://yderskov.com/erhverv" />
	<meta property="og:siteName" content="Yderskov Arkitekter" />
	<meta property="og:image" content="https://yderskov.com/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Erhvervsbyggeri — Arkitekttegnede kontorer | Yderskov" />
	<meta
		name="twitter:description"
		content="Vi tegner erhvervsbyggeri, der matcher jeres behov — fra kontorer til udlejningsboliger og ombygninger. Få arkitektrådgivning til aftalt fast pris."
	/>
	<meta name="twitter:image" content="https://yderskov.com/images/Assensvej Kontormiljø/Aalborg-Assensvej-kontormiljø.webp" />
	{@html `<script type="application/ld+json">${JSON.stringify(projectSchema).replace(/</g, '\\u003c')}</script>`}
</svelte:head>

<Breadcrumbs items={[{ label: 'Erhverv' }]} />
<Hero
	slides={[
		{ src: '/images/Hals Rækkehuse/Hals-Aalborgvej40-udlejning-.webp', alt: 'Udlejningsboliger i Hals — Arkitekttegnestuen Yderskov' }
	]}
	tag="Erhverv"
	subtitle="Erhverv"
	lines={[
		'Dine rammer sætter tonen for din forretning. Lad os tegne dem.',
		'Gratis og uforpligtende første idemøde. Vi kommer ud til jer.'
	]}
	italicLines={[0, 1]}
/>

<section class="s">
	<div class="s-inner">
		<div class="text-2col">
			<div>
				<span class="eyebrow">Erhvervsbyggeri</span>
				<h1 class="sec-hed">Erhvervsbyggeri<br />tegnet til jeres behov.</h1>
			</div>
			<div>
				<p class="body-p">
					Vi tegner erhvervsbyggeri der afspejler jeres virksomhed — fra funktionelle kontorlokaler til produktionsfaciliteter med arkitektonisk identitet. Læs mere om <a href="/om" class="text-link">vores samlede proces</a> eller se vores generelle <a href="/priser" class="text-link">priser på erhverv og bolig</a>.
				</p>
				<p class="body-p">
					Vi håndterer hele processen fra idé til indvielse — med focus på jeres budget og tidsplan.
				</p>
				<p class="body-p">
					<a href="#kontakt" class="text-link">→ Fortæl os om jeres projekt</a>
				</p>
			</div>
		</div>
	</div>
</section>

{#each projectGalleries as gallery, i (i)}
	<section class={`s${gallery.dark ? ' s-off' : ''}`}>
		<div class="s-inner">
			<div class="proj-header">
				<div>
					<span class="eyebrow">{gallery.eyebrow}</span>
					{#if 'beforeImages' in gallery && gallery.beforeImages}
						<span class="proj-ba-badge">
							<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
								<path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.85 1 6.5 2.5" />
								<path d="M21 3v6h-6" />
							</svg>
							Før / Efter
						</span>
					{/if}
					<h2 class="sec-hed" style="margin-bottom: 0; white-space: pre-line;">
						{gallery.title}
					</h2>
					{#if 'location' in gallery && gallery.location}
						<p class="proj-meta">
							{gallery.location}{gallery.size ? ` · ${gallery.size}` : ''}{gallery.year ? ` · ${gallery.year}` : ''}
						</p>
					{/if}
					{#if 'description' in gallery && gallery.description}
						<ProjectDescription text={gallery.description} />
					{/if}
				</div>
			</div>
			{#if 'afterLabel' in gallery}<p class="proj-grid-label">{gallery.afterLabel}</p>{/if}
			<ImageGrid images={gallery.images} />
			{#if 'beforeImages' in gallery && gallery.beforeImages}
				<p class="proj-grid-label" style="margin-top: 2rem;">{gallery.beforeLabel}</p>
				<ImageGrid images={gallery.beforeImages} />
			{/if}
		</div>
	</section>
{/each}

<section class="s">
	<div class="s-inner">
		<span class="eyebrow">Spørgsmål og svar</span>
		<h2 class="sec-hed">FAQ — erhverv</h2>
		<div class="faq-grid">
			{#each faqItems as item, i (i)}
				<div class="faq-item">
					<p class="faq-q">{item.q}</p>
					<p class="faq-a">{item.a}</p>
				</div>
			{/each}
		</div>
	</div>
</section>

<!-- Inspiration Galleri -->
<section class="s s-off">
	<div class="s-inner">
		<span class="eyebrow">Galleri</span>
		<h2 class="sec-hed">Inspiration</h2>
		<InspirationGallery />
	</div>
</section>

<CtaBand />

<section class="s form-bg" id="kontakt">
	<div class="s-inner">
		<div class="form-layout">
			<div class="form-meta">
				<span class="eyebrow">Kontakt os</span>
				<h2 class="sec-hed">Fortæl os om<br />jeres erhvervsprojekt</h2>
				<p style="margin-top: 1.5rem;">Ring eller skriv til os. Vi svarer inden 24 timer.</p>
				<p><a href="tel:29723427">29 72 34 27</a></p>
				<p><a href="mailto:cy@yderskov.com">cy@yderskov.com</a></p>
			</div>
			<ContactForm />
		</div>
	</div>
</section>
