// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import Image from '$lib/components/Image.svelte';
	import ContactForm from '$lib/components/ContactForm.svelte';
	import Breadcrumbs from '$lib/components/Breadcrumbs.svelte';
	import { posts } from '$lib/data/posts';
	import { parseParagraph, categoryLinks } from '$lib/parseParagraph';

	let { data }: { data: { post: import('$lib/data/posts').BlogPost } } = $props();

	const post = $derived(data.post);

	const dateParts = $derived(post.date.split('/').map((s) => s.trim()));
	const dateISO = $derived(
		dateParts.length === 3 ? `${dateParts[2]}-${dateParts[1]}-${dateParts[0]}` : undefined
	);
	const schemaImageUrl = $derived(
		post.image
			? `https://yderskov.com${post.image}`
			: 'https://yderskov.com/images/topbanner-new.webp'
	);
	const imageUrl = $derived(schemaImageUrl);

	const blogSchema = $derived({
		'@context': 'https://schema.org',
		'@type': 'BlogPosting',
		headline: post.title,
		description: post.description,
		image: schemaImageUrl,
		datePublished: dateISO,
		author: {
			'@type': 'Organization',
			name: 'Yderskov Arkitekter',
			url: 'https://yderskov.com/'
		},
		publisher: {
			'@type': 'Organization',
			name: 'Yderskov Arkitekter',
			logo: {
				'@type': 'ImageObject',
				// Google's Article/BlogPosting rich results only accept raster
				// logos (PNG/JPG/WebP) here — an SVG silently fails validation.
				url: 'https://yderskov.com/icon-512.png'
			}
		},
		mainEntityOfPage: {
			'@type': 'WebPage',
			'@id': `https://yderskov.com/blog/${post.slug}`
		}
	});

	const links = $derived(post.relatedLinks ?? categoryLinks[post.catKey] ?? []);
	const morePosts = $derived(posts.filter((p) => p.slug !== post.slug).slice(0, 3));
</script>

<svelte:head>
	<title>{post.metaTitle}</title>
	<meta name="description" content={post.description} />
	<link rel="canonical" href={`https://yderskov.com/blog/${post.slug}`} />
	<meta property="og:type" content="article" />
	<meta property="og:locale" content="da_DK" />
	<meta property="og:title" content={post.metaTitle} />
	<meta property="og:description" content={post.description} />
	<meta property="og:url" content={`https://yderskov.com/blog/${post.slug}`} />
	<meta property="og:siteName" content="Yderskov Arkitekter" />
	<meta property="og:image" content={imageUrl} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={post.metaTitle} />
	<meta name="twitter:description" content={post.description} />
	<meta name="twitter:image" content={imageUrl} />
	{@html `<script type="application/ld+json">${JSON.stringify(blogSchema).replace(/</g, '\\u003c')}</script>`}
</svelte:head>

<Breadcrumbs noHero items={[{ label: 'Blog', href: '/blog' }, { label: post.title }]} />

<article>
	<!-- Article header -->
	<section class="s" style="padding-bottom: 3rem;">
		<div class="s-inner" style="max-width: 740px;">
			<span class="eyebrow">{post.cat}</span>
			<h1 class="sec-hed" style="font-size: clamp(1.8rem, 4vw, 2.8rem); margin-bottom: 1.5rem;">
				{post.title}
			</h1>
			<p
				style="font-size: 0.72rem; font-weight: 300; color: var(--light); letter-spacing: 0.08em; margin-bottom: 2rem;"
			>
				{post.date}
			</p>
			<p
				style="font-size: 1.05rem; font-weight: 300; color: var(--sub); line-height: 1.75; border-left: 3px solid var(--border); padding-left: 1.25rem;"
			>
				{#each parseParagraph(post.lead) as seg, i (i)}{#if seg.type === 'text'}{seg.value}{:else}<a
						href={seg.href}
						target={seg.external ? '_blank' : undefined}
						rel={seg.external ? 'noopener noreferrer' : undefined}
						style="text-decoration: underline;">{seg.label}</a
					>{/if}{/each}
			</p>
			{#if post.images && post.images.length > 0}
				<div class="blog-gallery">
					{#each post.images as img, index (index)}
						<div style="border-radius: 12px; overflow: hidden; aspect-ratio: 4/3; position: relative;">
							<Image
								src={img}
								alt={`${post.title.includes('Arkitekttegnestuen Yderskov') ? post.title.replace(/ — Arkitekttegnestuen Yderskov$/, '') : post.title} - billede ${index + 1} — Arkitekttegnestuen Yderskov`}
								fill
								sizes="(max-width: 900px) 100vw, 50vw"
								style="object-fit: cover;"
							/>
						</div>
					{/each}
				</div>
			{:else if post.image}
				<div style="margin-top: 2.5rem; border-radius: 12px; overflow: hidden; aspect-ratio: 16/10; position: relative;">
					<Image
						src={post.image}
						alt={post.title.includes('Arkitekttegnestuen Yderskov') ? post.title : `${post.title} — Arkitekttegnestuen Yderskov`}
						fill
						sizes="(max-width: 900px) 100vw, 80vw"
						style="object-fit: cover;"
						priority
					/>
				</div>
			{/if}
		</div>
	</section>

	<!-- Article body -->
	<section class="s" style="padding-top: 2rem; background: var(--off);">
		<div class="s-inner" style="max-width: 740px;">
			{#each post.sections as section, i (i)}
				{#if section.type === 'case'}
					<div class="case-block">
						<span class="case-pill">Cases fra praksis</span>
						<h2 style="font-size: 1.05rem; font-weight: 400; color: var(--text); letter-spacing: -0.02em; margin-bottom: 0.85rem;">
							{section.heading}
						</h2>
						{#each section.paragraphs as p, j (j)}
							<p class="body-p">
								{#each parseParagraph(p) as seg, k (k)}{#if seg.type === 'text'}{seg.value}{:else}<a
										href={seg.href}
										target={seg.external ? '_blank' : undefined}
										rel={seg.external ? 'noopener noreferrer' : undefined}
										style="text-decoration: underline;">{seg.label}</a
									>{/if}{/each}
							</p>
						{/each}
					</div>
				{:else}
					<div style="margin-bottom: 2.5rem;">
						<h2 style="font-size: 1.05rem; font-weight: 400; color: var(--text); letter-spacing: -0.02em; margin-bottom: 0.85rem;">
							{section.heading}
						</h2>
						{#each section.paragraphs as p, j (j)}
							<p class="body-p">
								{#each parseParagraph(p) as seg, k (k)}{#if seg.type === 'text'}{seg.value}{:else}<a
										href={seg.href}
										target={seg.external ? '_blank' : undefined}
										rel={seg.external ? 'noopener noreferrer' : undefined}
										style="text-decoration: underline;">{seg.label}</a
									>{/if}{/each}
							</p>
						{/each}
					</div>
				{/if}
			{/each}
		</div>
	</section>

	<!-- Se også -->
	{#if links.length > 0}
		<section class="s" style="padding-top: 1rem; padding-bottom: 0;">
			<div class="s-inner" style="max-width: 740px;">
				<div class="see-also">
					<p class="see-also-label">Se også</p>
					<div class="see-also-links">
						{#each links as l, i (i)}
							<a href={l.href} class="see-also-link">{l.label} →</a>
						{/each}
					</div>
				</div>
			</div>
		</section>
	{/if}

	<!-- CTA strip -->
	<section class="s" style="padding-top: 3rem; padding-bottom: 3rem;">
		<div class="s-inner" style="max-width: 740px;">
			<div
				style="background: var(--dark); border-radius: 16px; padding: 2.5rem; display: flex; justify-content: space-between; align-items: center; gap: 2rem; flex-wrap: wrap;"
			>
				<div>
					<p style="font-size: 1rem; font-weight: 300; color: #fff; margin-bottom: 0.4rem;">
						Gratis og uforpligtende første møde
					</p>
					<p style="font-size: 0.8rem; font-weight: 300; color: rgba(255,255,255,0.55);">
						Vi svarer inden 24 timer
					</p>
				</div>
				<a
					href="/kontakt"
					style="background: #fff; color: var(--text); border-radius: 980px; padding: 0.6rem 1.4rem; font-size: 0.82rem; font-weight: 400; white-space: nowrap;"
				>
					Book gratis møde →
				</a>
			</div>
		</div>
	</section>
</article>

<!-- Contact form -->
<section class="s form-bg">
	<div class="s-inner" style="max-width: 900px;">
		<div class="form-layout">
			<div class="form-meta">
				<span class="eyebrow">Kontakt os</span>
				<h2 class="sec-hed">Fortæl os om<br />dit projekt</h2>
				<p style="margin-top: 1.5rem;">
					Ring eller skriv til os. Vi svarer inden 24 timer og tilbyder et gratis, uforpligtende møde.
				</p>
				<p><a href="tel:29723427">29 72 34 27</a></p>
				<p><a href="mailto:cy@yderskov.com">cy@yderskov.com</a></p>
			</div>
			<ContactForm />
		</div>
	</div>
</section>

<!-- More posts -->
<div class="blog-bg">
	<div class="blog-inner">
		<div class="blog-head">
			<h2 class="sec-hed">Flere indlæg</h2>
			<a href="/blog" class="blog-see">Se alle →</a>
		</div>
		<div class="bgrid">
			{#each morePosts as p (p.slug)}
				<a href={`/blog/${p.slug}`} class="bcard">
					<span class="bdate">{p.date}</span>
					<h3>{p.title}</h3>
					<p>{p.description}</p>
					<span class="blink">Læs mere →</span>
				</a>
			{/each}
		</div>
	</div>
</div>

// app/blog/[slug]/page.tsx
import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import ContactForm from "@/components/ContactForm";
import { getPost, posts, type RelatedLink } from "../posts";

function parseParagraph(text: string) {
  const linkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
  const parts = [];
  let lastIndex = 0;
  let match;

  while ((match = linkRegex.exec(text)) !== null) {
    const [fullMatch, label, url] = match;
    const matchIndex = match.index;

    if (matchIndex > lastIndex) {
      parts.push(text.substring(lastIndex, matchIndex));
    }

    const isExternal = url.startsWith("http");
    if (isExternal) {
      parts.push(
        <a key={matchIndex} href={url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: "underline" }}>
          {label}
        </a>
      );
    } else {
      parts.push(
        <Link key={matchIndex} href={url} style={{ textDecoration: "underline" }}>
          {label}
        </Link>
      );
    }

    lastIndex = linkRegex.lastIndex;
  }

  if (lastIndex < text.length) {
    parts.push(text.substring(lastIndex));
  }

  return parts.length > 0 ? parts : text;
}

const categoryLinks: Record<string, RelatedLink[]> = {
  villa: [
    { label: "Læs om Yderskov som arkitekt i Aalborg", href: "/arkitekt-aalborg" },
    { label: "Se vores villaprojekter med billeder", href: "/villaer" },
    { label: "Se om- og tilbygninger med billeder", href: "/tilbygninger" },
  ],
  sommerhus: [
    { label: "Se vores sommerhusprojekter med billeder", href: "/sommerhuse" },
    { label: "Beregn prisen på dit sommerhus", href: "/prisberegner" },
  ],
  arkitekt: [
    { label: "Læs om Yderskov som arkitekt i Aalborg", href: "/arkitekt-aalborg" },
    { label: "Beregn prisen på dit projekt", href: "/prisberegner" },
    { label: "Se vores priser", href: "/priser" },
  ],
  grund: [
    { label: "Læs om Yderskov som arkitekt i Aalborg", href: "/arkitekt-aalborg" },
    { label: "Se vores villaprojekter med billeder", href: "/villaer" },
    { label: "Se vores sommerhusprojekter med billeder", href: "/sommerhuse" },
  ],
  boligdetalje: [
    { label: "Læs om Yderskov som arkitekt i Aalborg", href: "/arkitekt-aalborg" },
    { label: "Se vores villaprojekter med billeder", href: "/villaer" },
    { label: "Se om- og tilbygninger med billeder", href: "/tilbygninger" },
  ],
};

export async function generateStaticParams() {
  return posts.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post || post.redirect) return {};
  
  const imageUrl = post.image ? `https://yderskov.com${post.image}` : "https://yderskov.com/images/topbanner-new.webp";

  return {
    title: post.metaTitle,
    description: post.description,
    alternates: { canonical: `https://yderskov.com/blog/${post.slug}` },
    openGraph: {
      type: "article",
      locale: "da_DK",
      title: post.metaTitle,
      description: post.description,
      url: `https://yderskov.com/blog/${post.slug}`,
      siteName: "Yderskov Arkitekter",
      images: [{ url: imageUrl }],
    },
    twitter: {
      card: "summary_large_image",
      title: post.metaTitle,
      description: post.description,
      images: [imageUrl],
    },
  };
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) notFound();
  if (post.redirect) redirect(post.redirect);

  const dateParts = post.date.split("/").map((s) => s.trim());
  const dateISO = dateParts.length === 3 ? `${dateParts[2]}-${dateParts[1]}-${dateParts[0]}` : undefined;

  const blogSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "headline": post.title,
    "description": post.description,
    "datePublished": dateISO,
    "author": {
      "@type": "Organization",
      "name": "Yderskov Arkitekter",
      "url": "https://yderskov.com/",
    },
    "publisher": {
      "@type": "Organization",
      "name": "Yderskov Arkitekter",
      "logo": {
        "@type": "ImageObject",
        "url": "https://yderskov.com/favicon.svg",
      },
    },
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": `https://yderskov.com/blog/${post.slug}`,
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(blogSchema) }}
      />
      <Nav />

      <article>
        {/* Article header */}
        <section className="s" style={{ paddingBottom: "3rem" }}>
          <div className="s-inner" style={{ maxWidth: "740px" }}>
            <span className="eyebrow">{post.cat}</span>
            <h1
              className="sec-hed"
              style={{ fontSize: "clamp(1.8rem, 4vw, 2.8rem)", marginBottom: "1.5rem" }}
            >
              {post.title}
            </h1>
            <p
              style={{
                fontSize: "0.72rem",
                fontWeight: 300,
                color: "var(--light)",
                letterSpacing: "0.08em",
                marginBottom: "2rem",
              }}
            >
              {post.date}
            </p>
            <p
              style={{
                fontSize: "1.05rem",
                fontWeight: 300,
                color: "var(--sub)",
                lineHeight: 1.75,
                borderLeft: "3px solid var(--border)",
                paddingLeft: "1.25rem",
              }}
            >
              {parseParagraph(post.lead)}
            </p>
            {post.images && post.images.length > 0 ? (
              <div className="blog-gallery">
                {post.images.map((img, index) => (
                  <div key={index} style={{ borderRadius: "12px", overflow: "hidden", aspectRatio: "4/3", position: "relative" }}>
                    <Image
                      src={img}
                      alt={`${post.title.includes("Arkitekttegnestuen Yderskov") ? post.title.replace(/ — Arkitekttegnestuen Yderskov$/, '') : post.title} - billede ${index + 1} — Arkitekttegnestuen Yderskov`}
                      fill
                      sizes="(max-width: 900px) 100vw, 50vw"
                      style={{ objectFit: "cover" }}
                    />
                  </div>
                ))}
              </div>
            ) : post.image ? (
              <div style={{ marginTop: "2.5rem", borderRadius: "12px", overflow: "hidden", aspectRatio: "16/10", position: "relative" }}>
                <Image
                  src={post.image}
                  alt={post.title.includes("Arkitekttegnestuen Yderskov") ? post.title : `${post.title} — Arkitekttegnestuen Yderskov`}
                  fill
                  sizes="(max-width: 900px) 100vw, 80vw"
                  style={{ objectFit: "cover" }}
                  priority
                />
              </div>
            ) : null}
          </div>
        </section>

        {/* Article body */}
        <section
          className="s"
          style={{ paddingTop: "2rem", background: "var(--off)" }}
        >
          <div className="s-inner" style={{ maxWidth: "740px" }}>
            {post.sections.map((section, i) =>
              section.type === "case" ? (
                <div key={i} className="case-block">
                  <span className="case-pill">Cases fra praksis</span>
                  <h2
                    style={{
                      fontSize: "1.05rem",
                      fontWeight: 400,
                      color: "var(--text)",
                      letterSpacing: "-0.02em",
                      marginBottom: "0.85rem",
                    }}
                  >
                    {section.heading}
                  </h2>
                  {section.paragraphs.map((p, j) => (
                    <p key={j} className="body-p">
                      {parseParagraph(p)}
                    </p>
                  ))}
                </div>
              ) : (
                <div key={i} style={{ marginBottom: "2.5rem" }}>
                  <h2
                    style={{
                      fontSize: "1.05rem",
                      fontWeight: 400,
                      color: "var(--text)",
                      letterSpacing: "-0.02em",
                      marginBottom: "0.85rem",
                    }}
                  >
                    {section.heading}
                  </h2>
                  {section.paragraphs.map((p, j) => (
                    <p key={j} className="body-p">
                      {parseParagraph(p)}
                    </p>
                  ))}
                </div>
              )
            )}
          </div>
        </section>

        {/* Se også */}
        {(() => {
          const links = post.relatedLinks ?? categoryLinks[post.catKey] ?? [];
          if (links.length === 0) return null;
          return (
            <section className="s" style={{ paddingTop: "1rem", paddingBottom: "0" }}>
              <div className="s-inner" style={{ maxWidth: "740px" }}>
                <div className="see-also">
                  <p className="see-also-label">Se også</p>
                  <div className="see-also-links">
                    {links.map((l, i) => (
                      <Link key={i} href={l.href} className="see-also-link">
                        {l.label} →
                      </Link>
                    ))}
                  </div>
                </div>
              </div>
            </section>
          );
        })()}

        {/* CTA strip */}
        <section className="s" style={{ paddingTop: "3rem", paddingBottom: "3rem" }}>
          <div className="s-inner" style={{ maxWidth: "740px" }}>
            <div
              style={{
                background: "var(--dark)",
                borderRadius: "16px",
                padding: "2.5rem",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                gap: "2rem",
                flexWrap: "wrap",
              }}
            >
              <div>
                <p
                  style={{
                    fontSize: "1rem",
                    fontWeight: 300,
                    color: "#fff",
                    marginBottom: "0.4rem",
                  }}
                >
                  Gratis og uforpligtende første møde
                </p>
                <p style={{ fontSize: "0.8rem", fontWeight: 300, color: "rgba(255,255,255,0.55)" }}>
                  Vi svarer inden 24 timer
                </p>
              </div>
              <Link
                href="/kontakt"
                style={{
                  background: "#fff",
                  color: "var(--text)",
                  borderRadius: "980px",
                  padding: "0.6rem 1.4rem",
                  fontSize: "0.82rem",
                  fontWeight: 400,
                  whiteSpace: "nowrap",
                }}
              >
                Book gratis møde →
              </Link>
            </div>
          </div>
        </section>
      </article>

      {/* Contact form */}
      <section className="s form-bg">
        <div className="s-inner" style={{ maxWidth: "900px" }}>
          <div className="form-layout">
            <div className="form-meta">
              <span className="eyebrow">Kontakt os</span>
              <h2 className="sec-hed">Fortæl os om<br />dit projekt</h2>
              <p style={{ marginTop: "1.5rem" }}>
                Ring eller skriv til os. Vi svarer inden 24 timer og tilbyder et gratis, uforpligtende møde.
              </p>
              <p>
                <a href="tel:29723427">29 72 34 27</a>
              </p>
              <p>
                <a href="mailto:cy@yderskov.com">cy@yderskov.com</a>
              </p>
            </div>
            <ContactForm />
          </div>
        </div>
      </section>

      {/* More posts */}
      <div className="blog-bg">
        <div className="blog-inner">
          <div className="blog-head">
            <h2 className="sec-hed">Flere indlæg</h2>
            <Link href="/blog" className="blog-see">
              Se alle →
            </Link>
          </div>
          <div className="bgrid">
            {posts
              .filter((p) => p.slug !== post.slug)
              .slice(0, 3)
              .map((p) => (
                <Link key={p.slug} href={`/blog/${p.slug}`} className="bcard">
                  <span className="bdate">{p.date}</span>
                  <h3>{p.title}</h3>
                  <p>{p.description}</p>
                  <span className="blink">Læs mere →</span>
                </Link>
              ))}
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
